// PixelStreamingCredentialProvider.h
#pragma once

#include <credentialprovider.h>
#include <windows.h>
#include <initguid.h> // For DEFINE_GUID

// TODO: Replace with a new GUID generated by user (e.g., using uuidgen)
// Example GUID:
DEFINE_GUID(CLSID_PixelStreamingCredentialProvider,
    0x1658137d, 0x7255, 0x429f, 0x9a, 0x2a, 0x63, 0x65, 0x53, 0xf2, 0xf5, 0xa0);

class CPixelStreamingCredentialProvider : public ICredentialProvider
{
public:
    // IUnknown
    IFACEMETHODIMP QueryInterface(REFIID riid, void** ppv) override;
    IFACEMETHODIMP_(ULONG) AddRef() override;
    IFACEMETHODIMP_(ULONG) Release() override;

    // ICredentialProvider
    IFACEMETHODIMP SetUsageScenario(CREDENTIAL_PROVIDER_USAGE_SCENARIO cpus, DWORD dwFlags) override;
    IFACEMETHODIMP SetSerialization(const CREDENTIAL_PROVIDER_SERIALIZATION* pcpcs) override;
    IFACEMETHODIMP Advise(ICredentialProviderEvents* pcpe, UINT_PTR upAdviseContext) override;
    IFACEMETHODIMP UnAdvise() override;
    IFACEMETHODIMP GetFieldDescriptorCount(DWORD* pdwCount) override;
    IFACEMETHODIMP GetFieldDescriptorAt(DWORD dwIndex, CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR** ppcpfd) override;
    IFACEMETHODIMP GetCredentialCount(DWORD* pdwCount, DWORD* pdwDefault, BOOL* pbAutoLogonWithDefault) override;
    IFACEMETHODIMP GetCredentialAt(DWORD dwIndex, ICredentialProviderCredential** ppcpc) override;

    CPixelStreamingCredentialProvider();
    ~CPixelStreamingCredentialProvider();

private:
    LONG _cRef;
    CREDENTIAL_PROVIDER_USAGE_SCENARIO _cpus;
    ICredentialProviderEvents* _pcpe;
    UINT_PTR _upAdviseContext;
    CREDENTIAL_PROVIDER_SERIALIZATION _cpcs;

private:
    static const CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR s_rgFieldDescriptors[];
    static const DWORD s_dwFieldDescriptorCount;
};

// Helper function to create a CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
HRESULT FieldDescriptorCoAllocCopy(
    const CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR& rcpfd,
    CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR** ppcpfd);

// Helper function to free a CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR
void FieldDescriptorFree(CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR* pcpfd);
